# Generated by Django 6.0.5 on 2026-05-12 22:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centroacopio',
            old_name='capacidad_maxima',
            new_name='capacidadTotal',
        ),
        migrations.AddField(
            model_name='centroacopio',
            name='capacidadUsada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='fechaActualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='unidadMedida',
            field=models.CharField(default='unidades', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ALIMENTOS', 'Alimentos'), ('ROPA', 'Ropa y Abrigo'), ('MEDICOS', 'Insumos Médicos'), ('HIGIENE', 'Higiene')], max_length=50),
        ),
    ]
