# Generated by Django 6.0.5 on 2026-05-15 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroAcopio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.TextField()),
                ('capacidadTotal', models.IntegerField()),
                ('capacidadUsada', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('ALIMENTOS', 'Alimentos'), ('ROPA', 'Ropa y Abrigo'), ('MEDICOS', 'Insumos Médicos'), ('HIGIENE', 'Higiene')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidadMedida', models.CharField(default='unidades', max_length=20)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.centroacopio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.producto')),
            ],
        ),
    ]
